/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type: "pdf" | "link" | "repo" | "other";
  title: string;
  description?: string;
  url: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon: string;
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level: "beginner" | "intermediate" | "advanced";
  price: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor: InstructorReference;
  category: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  durationMinutes: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | InstructorReference
  | CategoryReference
  | Course
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Lesson
  | Instructor
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../lib/sanity/queries/categories.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {  _id,  title,  "slug": slug.current,  description}
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
}>;

// Source: ../lib/sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  description,  "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    level,    price,    popular,    studentCount  }}
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    level: "advanced" | "beginner" | "intermediate";
    price: number;
    popular: boolean | null;
    studentCount: number | null;
  }>;
} | null;

// Source: ../lib/sanity/queries/categories.ts
// Variable: CATEGORY_SLUGS_QUERY
// Query: *[_type == "category" && defined(slug.current)] {  "slug": slug.current}
export type CATEGORY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../lib/sanity/queries/courses.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course"] | order(title asc) {  _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  level,  price,  popular,  studentCount,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  instructor->{   _id,  name,  "slug": slug.current,  photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  expertise },  category->{   _id,  title,  "slug": slug.current,  description }}
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    expertise: Array<string> | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
}>;

// Source: ../lib/sanity/queries/courses.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  summary,  coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  level,  price,  popular,  studentCount,  learningOutcomes[] {    _key,    icon,    title,    description  },  instructor->{      _id,  name,  "slug": slug.current,  photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  expertise,    bio  },  category->{   _id,  title,  "slug": slug.current,  description },  modules[] {    _key,    title,    summary,    lessons[]->{   _id,  title,  "slug": slug.current,  poster {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  durationMinutes,  freePreview,  studentCount,  keyPoints }  }}
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate";
  price: number;
  popular: boolean | null;
  studentCount: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string;
    title: string;
    description: string;
  }> | null;
  instructor: {
    _id: string;
    name: string;
    slug: string;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    expertise: Array<string> | null;
    bio: string | null;
  };
  category: {
    _id: string;
    title: string;
    slug: string;
    description: string | null;
  };
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      poster: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
      durationMinutes: number;
      freePreview: boolean | null;
      studentCount: number | null;
      keyPoints: Array<string> | null;
    }> | null;
  }> | null;
} | null;

// Source: ../lib/sanity/queries/courses.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] {  "slug": slug.current}
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../lib/sanity/queries/instructors.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc) {  _id,  name,  "slug": slug.current,  photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  expertise,  bio}
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  expertise: Array<string> | null;
  bio: string | null;
}>;

// Source: ../lib/sanity/queries/instructors.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {  _id,  name,  "slug": slug.current,  photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  expertise,  bio,  "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {    _id,    title,    "slug": slug.current,    summary,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },    level,    price,    popular,    studentCount  }}
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  expertise: Array<string> | null;
  bio: string | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    level: "advanced" | "beginner" | "intermediate";
    price: number;
    popular: boolean | null;
    studentCount: number | null;
  }>;
} | null;

// Source: ../lib/sanity/queries/instructors.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] {  "slug": slug.current}
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../lib/sanity/queries/lessons.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {  _id,  title,  "slug": slug.current,  videoUrl,  poster {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },  durationMinutes,  freePreview,  studentCount,  notes,  keyPoints,  proTip,  resources[] {    _key,    type,    title,    description,    url  },  "course": *[_type == "course" && references(^._id)][0] {    _id,    title,    "slug": slug.current,    coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop },    instructor->{      _id,      name,      "slug": slug.current,      photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  hotspot,  crop }    },    "module": modules[count(lessons[@._ref == ^.^._id]) > 0][0] {      _key,      title    }  }}
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  poster: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  durationMinutes: number;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "link" | "other" | "pdf" | "repo";
    title: string;
    description: string | null;
    url: string;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
      } | null;
    };
    module: {
      _key: string;
      title: string;
    } | null;
  } | null;
} | null;

// Source: ../lib/sanity/queries/lessons.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] {  "slug": slug.current}
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "category"] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  description\n}': CATEGORIES_QUERY_RESULT;
    '*[_type == "category" && slug.current == $slug][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  description,\n  "courses": *[_type == "course" && category._ref == ^._id] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    level,\n    price,\n    popular,\n    studentCount\n  }\n}': CATEGORY_BY_SLUG_QUERY_RESULT;
    '*[_type == "category" && defined(slug.current)] {\n  "slug": slug.current\n}': CATEGORY_SLUGS_QUERY_RESULT;
    '*[_type == "course"] | order(title asc) {\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  level,\n  price,\n  popular,\n  studentCount,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  expertise\n },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current,\n  description\n }\n}': COURSES_QUERY_RESULT;
    '*[_type == "course" && slug.current == $slug][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  level,\n  price,\n  popular,\n  studentCount,\n  learningOutcomes[] {\n    _key,\n    icon,\n    title,\n    description\n  },\n  instructor->{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  expertise\n,\n    bio\n  },\n  category->{ \n  _id,\n  title,\n  "slug": slug.current,\n  description\n },\n  modules[] {\n    _key,\n    title,\n    summary,\n    lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  poster { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  durationMinutes,\n  freePreview,\n  studentCount,\n  keyPoints\n }\n  }\n}': COURSE_BY_SLUG_QUERY_RESULT;
    '*[_type == "course" && defined(slug.current)] {\n  "slug": slug.current\n}': COURSE_SLUGS_QUERY_RESULT;
    '*[_type == "instructor"] | order(name asc) {\n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  expertise,\n  bio\n}': INSTRUCTORS_QUERY_RESULT;
    '*[_type == "instructor" && slug.current == $slug][0] {\n  _id,\n  name,\n  "slug": slug.current,\n  photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  expertise,\n  bio,\n  "courses": *[_type == "course" && instructor._ref == ^._id] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n    level,\n    price,\n    popular,\n    studentCount\n  }\n}': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '*[_type == "instructor" && defined(slug.current)] {\n  "slug": slug.current\n}': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '*[_type == "lesson" && slug.current == $slug][0] {\n  _id,\n  title,\n  "slug": slug.current,\n  videoUrl,\n  poster { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n  durationMinutes,\n  freePreview,\n  studentCount,\n  notes,\n  keyPoints,\n  proTip,\n  resources[] {\n    _key,\n    type,\n    title,\n    description,\n    url\n  },\n  "course": *[_type == "course" && references(^._id)][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n },\n    instructor->{\n      _id,\n      name,\n      "slug": slug.current,\n      photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  hotspot,\n  crop\n }\n    },\n    "module": modules[count(lessons[@._ref == ^.^._id]) > 0][0] {\n      _key,\n      title\n    }\n  }\n}': LESSON_BY_SLUG_QUERY_RESULT;
    '*[_type == "lesson" && defined(slug.current)] {\n  "slug": slug.current\n}': LESSON_SLUGS_QUERY_RESULT;
  }
}
